version: '3.1'

services:
  changjin_shopping_mall:
    image: changjinkube/knu_shoppingmall:nodejs1.0
    # build: ./nodejs
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    volumes:
      - /media/changjin/ubuntu_1TB/DB/nodejs/uploads:/github/uploads/uploads
    ports:
      - 89:3000
      - 5000:5000
      - 922:80

networks:
  default:
    external:
      name: mongo_default